name: sirs
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore: 4.17.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_pagination: ^3.1.0
  flutter:
    sdk: flutter
  get: 4.6.6
  panara_dialogs: ^0.1.4
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
