// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwvTxzybvTt557Crhohd9bM07hYPA3soQ',
    appId: '1:887282598200:web:ffc169e740a2fb0dfd01cd',
    messagingSenderId: '887282598200',
    projectId: 'sirs-db',
    authDomain: 'sirs-db.firebaseapp.com',
    storageBucket: 'sirs-db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcZ8wy_vIULK1llcgnNqN3ymJfUiw8OH8',
    appId: '1:887282598200:android:13a351148acd6694fd01cd',
    messagingSenderId: '887282598200',
    projectId: 'sirs-db',
    storageBucket: 'sirs-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2VHZmBkByZjdxfu_2NICBQuE_5LtEJAg',
    appId: '1:887282598200:ios:5f56b8e040a81413fd01cd',
    messagingSenderId: '887282598200',
    projectId: 'sirs-db',
    storageBucket: 'sirs-db.appspot.com',
    iosBundleId: 'com.sirs.sirs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2VHZmBkByZjdxfu_2NICBQuE_5LtEJAg',
    appId: '1:887282598200:ios:5f56b8e040a81413fd01cd',
    messagingSenderId: '887282598200',
    projectId: 'sirs-db',
    storageBucket: 'sirs-db.appspot.com',
    iosBundleId: 'com.sirs.sirs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwvTxzybvTt557Crhohd9bM07hYPA3soQ',
    appId: '1:887282598200:web:3e40200573f6c8defd01cd',
    messagingSenderId: '887282598200',
    projectId: 'sirs-db',
    authDomain: 'sirs-db.firebaseapp.com',
    storageBucket: 'sirs-db.appspot.com',
  );

}